# Connection settings
# TODO(romcheg): change to 127.0.0.1 after debug is done
OS_AUTH_URL: "http://172.18.163.4:8000/keystone/v2.0"
HTTP_PROXY: null
HTTP_TIMEOUT: 5

# Authentication settings
OS_USERNAME: "admin"
OS_PASSWORD: "admin"
OS_TENANT_NAME: "admin"
OS_REGION_NAME: "RegionOne"

# Performance tests settings
PERFORMANCE_PROFILING_TESTS: 0
PERF_TESTS_PATHS:
    perf_tests_base: "/tmp/fuelclient_performance_tests/tests/"
    last_performance_test: "/tmp/fuelclient_performance_tests/tests/last/"
    perf_tests_results: "/tmp/fuelclient_performance_tests/results/"
